"""add_characters_conversations_messages

Revision ID: a07523f0207c
Revises: 46700c8026a5
Create Date: 2025-12-11 21:15:16.248042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a07523f0207c'
down_revision: Union[str, None] = '46700c8026a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('personality_prompt', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('scenario_prompt', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('example_dialogues_prompt', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_column('characters', 'is_official')
    op.drop_column('characters', 'scenario')
    op.drop_column('characters', 'example_dialogues')
    op.drop_column('characters', 'personality')
    op.add_column('conversations', sa.Column('similarity_threshold', sa.Float(), nullable=True))
    op.add_column('conversations', sa.Column('top_k', sa.Integer(), nullable=True))
    op.drop_column('conversations', 'rag_similarity_threshold')
    op.drop_column('conversations', 'rag_top_k')
    op.drop_column('conversations', 'kb_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('kb_ids', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('rag_top_k', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('rag_similarity_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('conversations', 'top_k')
    op.drop_column('conversations', 'similarity_threshold')
    op.add_column('characters', sa.Column('personality', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('example_dialogues', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('scenario', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('is_official', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('characters', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('characters', 'tags')
    op.drop_column('characters', 'example_dialogues_prompt')
    op.drop_column('characters', 'scenario_prompt')
    op.drop_column('characters', 'personality_prompt')
    # ### end Alembic commands ###

